"""
Tool implementations for the Deep Agent.
Each tool is an async function — Deep Agents auto-wraps them.
Tools emit live progress via a callback set by the activity layer,
which publishes directly to the WebSocket stream.
"""

import json
import os
from typing import Callable, Awaitable

from tavily import TavilyClient


# ---------------------------------------------------------------------------
# Progress callback — set by the activity before the agent runs
# ---------------------------------------------------------------------------

_progress_cb: Callable[[str, str], Awaitable[None]] | None = None


def set_progress_callback(cb: Callable[[str, str], Awaitable[None]] | None):
    """Called by the activity to wire up live progress publishing."""
    global _progress_cb
    _progress_cb = cb


async def _emit(label: str, tool: str):
    """Emit a progress event if the callback is wired."""
    if _progress_cb:
        await _progress_cb(label, tool)


# ---------------------------------------------------------------------------
# Web search (via Tavily)
# ---------------------------------------------------------------------------

async def web_search(query: str) -> str:
    """Search the web for up-to-date information on any topic.

    Args:
        query: The search query string.

    Returns:
        A JSON string with a list of search results (title, url, snippet).
    """
    await _emit(f"Searching: {query}", "web_search")

    api_key = os.environ.get("TAVILY_API_KEY", "")
    if not api_key:
        return json.dumps({"error": "TAVILY_API_KEY not set"})
    client = TavilyClient(api_key=api_key)
    results = client.search(query, max_results=5)
    result_list = results.get("results", [])

    # Stream each URL live to the frontend
    for r in result_list:
        url = r.get("url", "")
        title = r.get("title", "")
        if url:
            await _emit(f"Read: {title} — {url}" if title else url, "web_search")

    return json.dumps(result_list, indent=2)


# ---------------------------------------------------------------------------
# PPTX generation
# ---------------------------------------------------------------------------

async def generate_pptx(title: str, slides: list[dict]) -> str:
    """Create a PowerPoint presentation and save it as presentation.pptx.

    Args:
        title: The presentation title for the title slide.
        slides: A list of dicts, each with 'title' (str) and 'bullets' (list[str]).

    Returns:
        The file path of the generated .pptx file.
    """
    from pptx import Presentation
    from pptx.util import Inches, Pt

    total = len(slides)
    await _emit(f"Building presentation: {title} ({total} slides)", "generate_pptx")

    prs = Presentation()

    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = "Generated by DeepAgent"

    # Content slides
    for idx, s in enumerate(slides, 1):
        await _emit(f"Building slide {idx} of {total}", "generate_pptx")

        slide_layout = prs.slide_layouts[1]  # Title + Content
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = s.get("title", "Slide")
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.clear()
        for i, bullet in enumerate(s.get("bullets", [])):
            if i == 0:
                tf.text = bullet
            else:
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 0

    output_dir = os.environ.get("ARTIFACT_DIR", "./artifacts")
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "presentation.pptx")
    prs.save(path)
    return f"Saved presentation to {path}"


# ---------------------------------------------------------------------------
# XLSX generation
# ---------------------------------------------------------------------------

async def generate_xlsx(title: str, headers: list[str], rows: list[list]) -> str:
    """Create an Excel spreadsheet and save it as results.xlsx.

    Args:
        title: The worksheet title / name.
        headers: Column header strings.
        rows: List of row data (each row is a list of cell values).

    Returns:
        The file path of the generated .xlsx file.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font

    await _emit(f"Writing {len(rows)} rows to spreadsheet: {title}", "generate_xlsx")

    wb = Workbook()
    ws = wb.active
    ws.title = title

    # Headers in bold
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True)

    # Data rows
    for row_idx, row_data in enumerate(rows, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws.cell(row=row_idx, column=col_idx, value=value)

    output_dir = os.environ.get("ARTIFACT_DIR", "./artifacts")
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "results.xlsx")
    wb.save(path)
    return f"Saved spreadsheet to {path}"


# ---------------------------------------------------------------------------
# HTML / landing page generation
# ---------------------------------------------------------------------------

async def generate_html(title: str, body_html: str) -> str:
    """Create an HTML landing page and save it as index.html.

    Args:
        title: The page <title> and visible heading.
        body_html: The HTML content for the page body (can include tags).

    Returns:
        The file path of the generated .html file.
    """
    await _emit(f"Generating landing page: {title}", "generate_html")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; color: #333; }}
        h1 {{ color: #1a1a2e; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    {body_html}
</body>
</html>"""

    output_dir = os.environ.get("ARTIFACT_DIR", "./artifacts")
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "index.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return f"Saved landing page to {path}"
